version: '3'
services:
  backend:
    build: ./backend
    command: python asgi.py
    volumes:
      - ./backend:/home/appuser/
    ports:
      - 8080:8080
  web:
    build: ./
    ### Use gunicorn for deployment.
    # command: gunicorn wsgi:app --bind 0.0.0.0:8080 --workers=4 --reload
    ### Use flask server for development.
    command: flask --app wsgi --debug run --host 0.0.0.0 --port 8080
    volumes:
      - ./:/home/appuser/
    ports:
      - 8080:8080